apiVersion: v1
kind: Service
metadata:
  name: register-service2
  namespace: production # chart
spec:
  selector:
    app: register #chart for blue green attachement.
  ports:
    - type: ClusterIP
      port: 8080
      targetPort: 8080