apiVersion: v1
kind: Secret
metadata:
  name: register-secret
type: Opaque
stringData:
  # API Gateway credentials
  APISIX_ADMIN_KEY: "ref+vault://secret/data/apisix#admin_key"
  APISIX_CONSUMER_NAME: "ref+vault://secret/data/apisix#consumer_name"
  APISIX_CONSUMER_KEY: "ref+vault://secret/data/apisix#consumer_key"

  # RabbitMQ credentials
  RABBITMQ_DEFAULT_PASS: "ref+vault://secret/data/rabbitmq#default_pass"
  RABBITMQ_PORT: "ref+vault://secret/data/rabbitmq#port"

  # Database credentials
  DB_USER: "ref+vault://secret/data/database#user"
  DB_PASSWORD: "ref+vault://secret/data/database#password"