apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: spot-first
spec:
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 168h

  template:
    spec:
      requirements:

        # Prefer SPOT
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot","on-demand"]

        # Restrict instance types (LAB OPTIMIZED)
        - key: node.kubernetes.io/instance-type
          operator: In
          values:
            - t3.medium
            - t3.large
            - m7i-flex.large
            - c7i-flex.large

      nodeClassRef:
        name: default