name: "Composite Sonar Scan"
description: "A composite action to perform SonarQube analysis on a specified service path with given arguments."

inputs:
  service-path:
    description: "The path to the service directory to be analyzed by SonarQube."
    required: true

  project-key:
    description: "The SonarQube project key for the analysis."
    required: true

  arguments:
    description: "Additional arguments for the SonarQube scanner."
    required: true

  command:
    description: "The command to build the project before running SonarQube analysis (e.g., 'mvn clean compile'). If not provided, the build step will be skipped."
    required: false

runs:
  using: "composite"
  steps:
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@v2
      with:
        projectBaseDir: ${{ inputs.service-path }}
        args: >
          -Dsonar.projectKey=${{inputs.project-key}}
          ${{ inputs.arguments}}
      env:
        SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ env.SONAR_HOST_URL }}
