name: ci login # ci code, ci terraform with atlantis, cd ec2 with ssh(to do docker run), cd ec2 with ssh(to do npm start)
                          # cd k8s with kubeconfig(to do k apply or helm install), cd k8s with argocd(none image changes), cd k8s(image via value.yaml or deploy.yaml) with argocd. 

permissions: #permission for reports to be uploaded to GitHub Security tab.
  contents: read # for checkout action
  security-events: write # for uploading sarif reports to security tab
  actions: read # for reusable workflow

on: # a pull request from feature branch(this is the branch that developers work on) to main branch. then on merge request to main branch, underneath a push event is triggered for main branch.
  push:
    branches: [main]
    paths:
      - '.github/workflows/ci_login.yaml'
      - 'services/login/**'
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/ci_login.yaml'
      - 'services/login/**'

env:
  NODE_VERSION: 20.20.0

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/login
    steps:
      - name: Checkout code(test)
        uses: actions/checkout@v4

      - name: Setup Node.js(test)
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: npm 
          cache-dependency-path: ./services/login/package-lock.json

      - name: Install dependencies(test)
        run: npm ci

      - name: Run tests with coverage and JUnit reporting
        run: npm test -- --coverage --ci --reporters=default --reporters=jest-junit

      - name: Upload JUnit Report
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: ./services/login/junit.xml 

      - name: Upload Coverage Report 
        uses: actions/upload-artifact@v4 
        with:
          name: coverage-report
          path: ./services/login/coverage/ 

  sonar: 
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/login
    steps:
      - name: Checkout code(sonar)
        uses: actions/checkout@v4

      - name: Setup Node.js(sonar)
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: npm 
          cache-dependency-path: services/login/package-lock.json

      - name: Install dependencies(sonar)
        run: npm ci

      - name: Run SonarQube Analysis
        uses: ./.github/actions/composite_sonar
        with:
          service-path: services/login
          project-key: login-service
          coverage-path: >
            -Dsonar.sources=.
            -Dsonar.tests=.
            -Dsonar.test.inclusions=**/*.test.js
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  dependency-scan:
    uses: ./.github/workflows/reuse_dependency_scan.yaml
    with:
      service-path: services/login
      

  build-and-image-scan:
    needs: [dependency-scan, sonar, test] # added sonar and test-login as dependencies for build and image scan.
    uses: ./.github/workflows/reuse_build_scan.yaml
    with:
      service-path: services/login
      image_name: login-service
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
