name: ci register # ci code, ci terraform with atlantis, cd ec2 with ssh(to do docker run), cd ec2 with ssh(to do npm start)
                          # cd k8s with kubeconfig(to do k apply or helm install), cd k8s with argocd(none image changes), cd k8s(image via value.yaml or deploy.yaml) with argocd. 

permissions: #permission for reports to be uploaded to GitHub Security tab.
  contents: read # for checkout action
  security-events: write # for uploading sarif reports to security tab
  actions: read # for reusable workflow

on: # a pull request from feature branch(this is the branch that developers work on) to main branch. then on merge request to main branch, underneath a push event is triggered for main branch.
  push:
    branches: [main]
    paths:
      - '.github/workflows/ci_register.yaml' # correction 6. removed removable-workflow path for both push and pr. and also worflows was missing in one. seems to be correct in other CIs.
      - 'services/register/**'
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/ci_register.yaml'
      - 'services/register/**'

env:
  JAVA_VERSION: 21

jobs:
  test-java:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/register # correction 1 services/register from ${{ env.SERVICE_PATH }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - run: mvn clean test

      - uses: actions/upload-artifact@v4
        with:
          name: java-test-report
          path: services/register/target/surefire-reports/

  sonar: #correction 8. removed if: false from sonar job to enable it.
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/register
    steps: # correction 12. using composite actions now with this special path convention.
      - uses: ./.github/actions/composite_sonar #correction 2 ./.github/workflows/reusable-worflow/reuse_sonar.yaml from .github/reusable-workflow/reuse_sonar.yaml
        with:
          service-path: services/register
          project-key: register-service
          arguments: > #correction 9. changed Dsonar.tests from src/test to src. correction 10. added dsonar.sources in ci from reusesable ci.
              -Dsonar.sources=src/main
              -Dsonar.tests=src/test/java
              -Dsonar.java.binaries=target/classes
              -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml 
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  dependency-scan:
    uses: ./.github/workflows/reuse_dependency_scan.yaml #correction 3 .github/workflows/reuse_dependency_scan.yaml from .github/reusable-workflow/reuse_dependency_scan.yaml
    with:
      service-path: services/register
      

  build-and-image-scan:
    needs: [dependency-scan, sonar, test-java] #correction 7. added sonar and test-java as dependencies for build and image scan.
    uses: ./.github/workflows/reuse_build_scan.yaml
    with:
      service-path: services/register #correction 4. service-path provided
      image_name: register-service #correction 5. image_name provided as a hard coded value.
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
